In [29]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [30]:
df = pd.read_csv(r"C:\Users\user\Downloads\data.csv")

In [31]:
df

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
0,0,0,HP,Victus 15-fb0157AX Gaming Laptop,49900,73.000000,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8GB,DDR4,512GB,SSD,4GB AMD Radeon RX 6500M,15.6,1920.0,1080.0,Windows 11 OS,1
1,1,1,HP,15s-fq5007TU Laptop,39900,60.000000,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
2,2,2,Acer,One 14 Z8-415 Laptop,26990,69.323529,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,1
3,3,3,Lenovo,Yoga Slim 6 14IAP8 82WU0095IN Laptop,59729,66.000000,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",16GB,LPDDR5,512GB,SSD,Intel Integrated Iris Xe,14.0,2240.0,1400.0,Windows 11 OS,1
4,4,4,Apple,MacBook Air 2020 MGND3HN Laptop,69990,69.323529,Apple M1,Octa Core (4P + 4E),8GB,DDR4,256GB,SSD,Apple M1 Integrated Graphics,13.3,2560.0,1600.0,Mac OS,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
888,926,1015,Asus,Vivobook 15X 2023 K3504VAB-NJ321WS Laptop,44990,69.323529,13th Gen ‎Intel Core i3 1315U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Integrated Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
889,927,1016,Asus,TUF A15 FA577RM-HQ032WS Laptop,110000,71.000000,6th Gen AMD Ryzen 7 6800H,"Octa Core, 16 Threads",16GB,DDR,1TB,SSD,6GB NVIDIA GeForce RTX 3060,15.6,2560.0,1440.0,Windows 11 OS,1
890,928,1017,Asus,ROG Zephyrus G14 2023 GA402XV-N2034WS Gaming L...,189990,89.000000,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",32GB,DDR5,1TB,SSD,8GB NVIDIA GeForce RTX 4060,14.0,2560.0,1600.0,Windows 11 OS,1
891,929,1018,Asus,TUF Gaming F15 2023 FX507VU-LP083WS Gaming Laptop,129990,73.000000,13th Gen Intel Core i7 13700H,"14 Cores (6P + 8E), 20 Threads",16GB,DDR4,512GB,SSD,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,Windows 11 OS,1
892,930,1019,Asus,TUF Gaming A15 2023 FA577XU-LP041WS Gaming Laptop,131990,84.000000,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",16GB,DDR4,1TB,SSD,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,Windows 11 OS,1

In [32]:
df.drop(['Unnamed: 0.1','Unnamed: 0','spec_rating','Ram_type','ROM_type','name'],axis=1,inplace=True)

In [33]:
df

,brand,price,processor,CPU,Ram,ROM,GPU,display_size,resolution_width,resolution_height,OS,warranty
0,HP,49900,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8GB,512GB,4GB AMD Radeon RX 6500M,15.6,1920.0,1080.0,Windows 11 OS,1
1,HP,39900,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8GB,512GB,Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
2,Acer,26990,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,512GB,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,1
3,Lenovo,59729,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",16GB,512GB,Intel Integrated Iris Xe,14.0,2240.0,1400.0,Windows 11 OS,1
4,Apple,69990,Apple M1,Octa Core (4P + 4E),8GB,256GB,Apple M1 Integrated Graphics,13.3,2560.0,1600.0,Mac OS,1
...,...,...,...,...,...,...,...,...,...,...,...,...
888,Asus,44990,13th Gen ‎Intel Core i3 1315U,"Hexa Core (2P + 4E), 8 Threads",8GB,512GB,Integrated Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
889,Asus,110000,6th Gen AMD Ryzen 7 6800H,"Octa Core, 16 Threads",16GB,1TB,6GB NVIDIA GeForce RTX 3060,15.6,2560.0,1440.0,Windows 11 OS,1
890,Asus,189990,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",32GB,1TB,8GB NVIDIA GeForce RTX 4060,14.0,2560.0,1600.0,Windows 11 OS,1
891,Asus,129990,13th Gen Intel Core i7 13700H,"14 Cores (6P + 8E), 20 Threads",16GB,512GB,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,Windows 11 OS,1
892,Asus,131990,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",16GB,1TB,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,Windows 11 OS,1

In [34]:
df.isna().sum()

brand                0
price                0
processor            0
CPU                  0
Ram                  0
ROM                  0
GPU                  0
display_size         0
resolution_width     0
resolution_height    0
OS                   0
warranty             0
dtype: int64

In [35]:
df.duplicated().sum()

np.int64(6)

In [38]:
df['Ram'].unique()

<StringArray>
['8GB', '16GB', '4GB', '32GB', '2GB', '12GB', '64GB']
Length: 7, dtype: str

In [39]:
ram_dict = {
    '8GB':8, '16GB':16, '4GB':4, '32GB':32, '2GB':2, '12GB':12, '64GB':64
}

In [40]:
df['Ram'] = df['Ram'].map(ram_dict)

In [41]:
df

,brand,price,processor,CPU,Ram,ROM,GPU,display_size,resolution_width,resolution_height,OS,warranty
0,HP,49900,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8,512GB,4GB AMD Radeon RX 6500M,15.6,1920.0,1080.0,Windows 11 OS,1
1,HP,39900,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8,512GB,Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
2,Acer,26990,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8,512GB,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,1
3,Lenovo,59729,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",16,512GB,Intel Integrated Iris Xe,14.0,2240.0,1400.0,Windows 11 OS,1
4,Apple,69990,Apple M1,Octa Core (4P + 4E),8,256GB,Apple M1 Integrated Graphics,13.3,2560.0,1600.0,Mac OS,1
...,...,...,...,...,...,...,...,...,...,...,...,...
888,Asus,44990,13th Gen ‎Intel Core i3 1315U,"Hexa Core (2P + 4E), 8 Threads",8,512GB,Integrated Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
889,Asus,110000,6th Gen AMD Ryzen 7 6800H,"Octa Core, 16 Threads",16,1TB,6GB NVIDIA GeForce RTX 3060,15.6,2560.0,1440.0,Windows 11 OS,1
890,Asus,189990,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",32,1TB,8GB NVIDIA GeForce RTX 4060,14.0,2560.0,1600.0,Windows 11 OS,1
891,Asus,129990,13th Gen Intel Core i7 13700H,"14 Cores (6P + 8E), 20 Threads",16,512GB,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,Windows 11 OS,1
892,Asus,131990,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",16,1TB,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,Windows 11 OS,1

In [42]:
df['ROM'].unique()

<StringArray>
['512GB', '256GB', '128GB', '64GB', '1TB', '32GB', '2TB']
Length: 7, dtype: str

In [44]:
df['ROM'] = df['ROM'].map({'512GB':512, '256GB':256, '128GB':128, '64GB':64, '1TB':1000, '32GB':32, '2TB':2000})

In [45]:
df

,brand,price,processor,CPU,Ram,ROM,GPU,display_size,resolution_width,resolution_height,OS,warranty
0,HP,49900,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8,512,4GB AMD Radeon RX 6500M,15.6,1920.0,1080.0,Windows 11 OS,1
1,HP,39900,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8,512,Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
2,Acer,26990,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8,512,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,1
3,Lenovo,59729,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",16,512,Intel Integrated Iris Xe,14.0,2240.0,1400.0,Windows 11 OS,1
4,Apple,69990,Apple M1,Octa Core (4P + 4E),8,256,Apple M1 Integrated Graphics,13.3,2560.0,1600.0,Mac OS,1
...,...,...,...,...,...,...,...,...,...,...,...,...
888,Asus,44990,13th Gen ‎Intel Core i3 1315U,"Hexa Core (2P + 4E), 8 Threads",8,512,Integrated Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
889,Asus,110000,6th Gen AMD Ryzen 7 6800H,"Octa Core, 16 Threads",16,1000,6GB NVIDIA GeForce RTX 3060,15.6,2560.0,1440.0,Windows 11 OS,1
890,Asus,189990,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",32,1000,8GB NVIDIA GeForce RTX 4060,14.0,2560.0,1600.0,Windows 11 OS,1
891,Asus,129990,13th Gen Intel Core i7 13700H,"14 Cores (6P + 8E), 20 Threads",16,512,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,Windows 11 OS,1
892,Asus,131990,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",16,1000,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,Windows 11 OS,1

In [46]:
df['OS'].unique()

<StringArray>
[     'Windows 11 OS',             'Mac OS',      'Android 11 OS',
             'DOS OS',      'Windows 10 OS',     'Windows 10  OS',
          'Chrome OS',         'Windows OS',          'Ubuntu OS',
    'Mac Catalina OS',         'DOS 3.0 OS',     'Windows 11  OS',
 'Mac High Sierra OS',   'Mac 10.15.3\t OS']
Length: 14, dtype: str

In [47]:
os_dict = {
     'Windows 11 OS':0,             'Mac OS':1,      'Android 11 OS':2,
             'DOS OS':3,      'Windows 10 OS':4,     'Windows 10  OS':5,
          'Chrome OS':6,         'Windows OS':7,          'Ubuntu OS':8,
    'Mac Catalina OS':9,         'DOS 3.0 OS':10,     'Windows 11  OS':11,
 'Mac High Sierra OS':12,   'Mac 10.15.3\t OS':13
}

In [49]:
df['OS'] = df['OS'].map(os_dict)

In [50]:
df

,brand,price,processor,CPU,Ram,ROM,GPU,display_size,resolution_width,resolution_height,OS,warranty
0,HP,49900,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8,512,4GB AMD Radeon RX 6500M,15.6,1920.0,1080.0,0,1
1,HP,39900,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8,512,Intel UHD Graphics,15.6,1920.0,1080.0,0,1
2,Acer,26990,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8,512,Intel Iris Xe Graphics,14.0,1920.0,1080.0,0,1
3,Lenovo,59729,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",16,512,Intel Integrated Iris Xe,14.0,2240.0,1400.0,0,1
4,Apple,69990,Apple M1,Octa Core (4P + 4E),8,256,Apple M1 Integrated Graphics,13.3,2560.0,1600.0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
888,Asus,44990,13th Gen ‎Intel Core i3 1315U,"Hexa Core (2P + 4E), 8 Threads",8,512,Integrated Intel UHD Graphics,15.6,1920.0,1080.0,0,1
889,Asus,110000,6th Gen AMD Ryzen 7 6800H,"Octa Core, 16 Threads",16,1000,6GB NVIDIA GeForce RTX 3060,15.6,2560.0,1440.0,11,1
890,Asus,189990,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",32,1000,8GB NVIDIA GeForce RTX 4060,14.0,2560.0,1600.0,0,1
891,Asus,129990,13th Gen Intel Core i7 13700H,"14 Cores (6P + 8E), 20 Threads",16,512,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,0,1
892,Asus,131990,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",16,1000,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,0,1

In [52]:
df['brand'].unique()

<StringArray>
[       'HP',      'Acer',    'Lenovo',     'Apple',      'Dell',      'Asus',
   'Samsung',   'Ultimus', 'Primebook',       'MSI',   'Infinix',     'Wings',
     'Honor', 'Zebronics',    'Xiaomi',     'iBall',     'Chuwi',    'Realme',
     'Avita',    'Walker',    'Huawei',     'Tecno',  'Gigabyte',      'Vaio',
 'Microsoft',   'Fujitsu',        'LG',   'Ninkear',     'Razer',       'AXL']
Length: 30, dtype: str

In [53]:
brand_dict = {
    'HP':0,      'Acer':1,    'Lenovo':2,     'Apple':3,      'Dell':4,      'Asus':5,
   'Samsung':6,   'Ultimus':7, 'Primebook':8,       'MSI':9,   'Infinix':10,     'Wings':11,
     'Honor':12, 'Zebronics':13,    'Xiaomi':14,     'iBall':15,     'Chuwi':16,    'Realme':17,
     'Avita':18,    'Walker':19,    'Huawei':20,     'Tecno':21,  'Gigabyte':22,      'Vaio':23,
 'Microsoft':24,   'Fujitsu':25,        'LG':26,   'Ninkear':27,     'Razer':28,       'AXL':29
}

In [54]:
df['brand'] = df['brand'].map(brand_dict)

In [55]:
df

,brand,price,processor,CPU,Ram,ROM,GPU,display_size,resolution_width,resolution_height,OS,warranty
0,0,49900,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8,512,4GB AMD Radeon RX 6500M,15.6,1920.0,1080.0,0,1
1,0,39900,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8,512,Intel UHD Graphics,15.6,1920.0,1080.0,0,1
2,1,26990,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8,512,Intel Iris Xe Graphics,14.0,1920.0,1080.0,0,1
3,2,59729,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",16,512,Intel Integrated Iris Xe,14.0,2240.0,1400.0,0,1
4,3,69990,Apple M1,Octa Core (4P + 4E),8,256,Apple M1 Integrated Graphics,13.3,2560.0,1600.0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
888,5,44990,13th Gen ‎Intel Core i3 1315U,"Hexa Core (2P + 4E), 8 Threads",8,512,Integrated Intel UHD Graphics,15.6,1920.0,1080.0,0,1
889,5,110000,6th Gen AMD Ryzen 7 6800H,"Octa Core, 16 Threads",16,1000,6GB NVIDIA GeForce RTX 3060,15.6,2560.0,1440.0,11,1
890,5,189990,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",32,1000,8GB NVIDIA GeForce RTX 4060,14.0,2560.0,1600.0,0,1
891,5,129990,13th Gen Intel Core i7 13700H,"14 Cores (6P + 8E), 20 Threads",16,512,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,0,1
892,5,131990,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",16,1000,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,0,1

In [56]:
df['CPU'].unique()

<StringArray>
[          'Hexa Core, 12 Threads',  'Hexa Core (2P + 4E), 8 Threads',
            'Dual Core, 4 Threads',  '12 Cores (4P + 8E), 16 Threads',
             'Octa Core (4P + 4E)', 'Octa Core (4P + 4E), 12 Threads',
  '10 Cores (2P + 8E), 12 Threads',            'Dual Core, 2 Threads',
                       'Octa Core',            'Quad Core, 8 Threads',
  '14 Cores (6P + 8E), 20 Threads',           'Octa Core, 16 Threads',
            'Octa Core, 8 Threads', '24 Cores (8P + 16E), 32 Threads',
  '10 Cores (6P + 4E), 16 Threads',            '14 Cores, 20 Threads',
            'Quad Core, 4 Threads',                       'Quad Core',
    '5 Cores (1P + 4E), 6 Threads',  '16 Cores (8P + 8E), 24 Threads',
            '16 Cores, 32 Threads',              '14 Cores (6P + 8E)',
                        '12 Cores',            '10 Cores, 12 Threads',
           'Octa Core, 12 Threads',              '10 Cores (8P + 2E)',
                        '10 Cores',             '24 Cores (8P + 16E)',
                      '20 Threads']
Length: 29, dtype: str

In [57]:
cpu_dict = {
    "10 Cores": 0, "10 Cores (2P + 8E), 12 Threads": 1, "10 Cores (6P + 4E), 16 Threads": 2,
    "10 Cores (8P + 2E)": 3, "10 Cores, 12 Threads": 4, "12 Cores": 5,
    "12 Cores (4P + 8E), 16 Threads": 6, "14 Cores (6P + 8E)": 7, "14 Cores (6P + 8E), 20 Threads": 8,
    "14 Cores, 20 Threads": 9, "16 Cores (8P + 8E), 24 Threads": 10, "16 Cores, 32 Threads": 11,
    "20 Threads": 12, "24 Cores (8P + 16E)": 13, "24 Cores (8P + 16E), 32 Threads": 14,
    "5 Cores (1P + 4E), 6 Threads": 15, "Dual Core, 2 Threads": 16, "Dual Core, 4 Threads": 17,
    "Hexa Core (2P + 4E), 8 Threads": 18, "Hexa Core, 12 Threads": 19, "Octa Core": 20,
    "Octa Core (4P + 4E)": 21, "Octa Core (4P + 4E), 12 Threads": 22, "Octa Core, 12 Threads": 23,
    "Octa Core, 16 Threads": 24, "Octa Core, 8 Threads": 25, "Quad Core": 26,
    "Quad Core, 4 Threads": 27, "Quad Core, 8 Threads": 28
}

In [58]:
df['CPU'] = df['CPU'].map(cpu_dict)

In [59]:
df

,brand,price,processor,CPU,Ram,ROM,GPU,display_size,resolution_width,resolution_height,OS,warranty
0,0,49900,5th Gen AMD Ryzen 5 5600H,19,8,512,4GB AMD Radeon RX 6500M,15.6,1920.0,1080.0,0,1
1,0,39900,12th Gen Intel Core i3 1215U,18,8,512,Intel UHD Graphics,15.6,1920.0,1080.0,0,1
2,1,26990,11th Gen Intel Core i3 1115G4,17,8,512,Intel Iris Xe Graphics,14.0,1920.0,1080.0,0,1
3,2,59729,12th Gen Intel Core i5 1240P,6,16,512,Intel Integrated Iris Xe,14.0,2240.0,1400.0,0,1
4,3,69990,Apple M1,21,8,256,Apple M1 Integrated Graphics,13.3,2560.0,1600.0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
888,5,44990,13th Gen ‎Intel Core i3 1315U,18,8,512,Integrated Intel UHD Graphics,15.6,1920.0,1080.0,0,1
889,5,110000,6th Gen AMD Ryzen 7 6800H,24,16,1000,6GB NVIDIA GeForce RTX 3060,15.6,2560.0,1440.0,11,1
890,5,189990,7th Gen AMD Ryzen 9 7940HS,24,32,1000,8GB NVIDIA GeForce RTX 4060,14.0,2560.0,1600.0,0,1
891,5,129990,13th Gen Intel Core i7 13700H,8,16,512,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,0,1
892,5,131990,7th Gen AMD Ryzen 9 7940HS,24,16,1000,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,0,1

In [60]:
df['GPU'].unique()

<StringArray>
[      '4GB AMD Radeon RX 6500M',            'Intel UHD Graphics',
        'Intel Iris Xe Graphics',      'Intel Integrated Iris Xe',
  'Apple M1 Integrated Graphics',   '6GB NVIDIA GeForce RTX 4050',
                 'Intel Iris Xe',          'Intel Integrated UHD',
 'Intel Integrated UHD Graphics',   '4GB NVIDIA GeForce RTX 3050',
 ...
                     'Intel UHD',   '8GB Nvidia GeForce RTX 4060',
   '6GB Nvidia GeForce RTX 4050',      '2GB NVIDIA GeForce MX570',
   '8GB NVIDIA Geforce RTX 4060',           '4GB Nvidia RTX 3050',
  '4GB NVIDIA GeForce GTX 1650 ',   '6GB NVIDIA GEFORCE RTX 4050',
          'Intel UHD Integrated',      '4GB AMD Radeon RX 5600M ']
Length: 134, dtype: str

In [61]:
df['processor'].unique()

<StringArray>
[        '5th Gen AMD Ryzen 5 5600H',      '12th Gen Intel Core i3 1215U',
     '11th Gen Intel Core i3 1115G4',      '12th Gen Intel Core i5 1240P',
                          'Apple M1',     '13th Gen Intel Core i5 13420H',
     '12th Gen Intel Core i5 12500H',      '12th Gen Intel Core i7 1255U',
              'Intel Celeron  N4020',                  'MediaTek MTK8788',
 ...
    '13th Gen Intel Core i5 13500H ',        '7th Gen AMD Ryzen 7 7745HX',
        '5th Gen AMD Ryzen 5  5500u',                     'Intel Core i7',
         '13th Gen Intel 7 13700HX ',        'Intel Pentium Silver N6000',
         '5th Gen AMD Ryzen 7 5800U', '7th Gen AMD Ryzen 7040 Series 040',
   '13th Gen Intel Core i9 13900HX ',     '13th Gen ‎Intel Core i3 1315U']
Length: 184, dtype: str