### Pandas
`pandas` is one of the most popular Python libraries for data analysis and manipulation. It provides powerful tools to work with tables, spreadsheets, CSV files, databases, and time-series data.

In [540]:
import os
import numpy as np 
import pandas as pd

In [541]:
df = pd.read_csv(r"C:\Users\user\OneDrive\Desktop\Data Science\ML\Projects\BIke prediction\Used_Bikes.csv")          #df = data frame
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [542]:
df.head()       #by default return top 5 rows

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha

In [543]:
df.head(10)

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
5,Yamaha FZs 150cc,53499.0,Delhi,25000.0,First Owner,6.0,150.0,Yamaha
6,Honda CB Hornet 160R ABS DLX,85000.0,Delhi,8200.0,First Owner,3.0,160.0,Honda
7,Hero Splendor Plus Self Alloy 100cc,45000.0,Delhi,12645.0,First Owner,3.0,100.0,Hero
8,Royal Enfield Thunderbird X 350cc,145000.0,Bangalore,9190.0,First Owner,3.0,350.0,Royal Enfield
9,Royal Enfield Classic Desert Storm 500cc,88000.0,Delhi,19000.0,Second Owner,7.0,500.0,Royal Enfield

In [544]:
df.tail()           #by default returns 5 rows from bottom

,bike_name,price,city,kms_driven,owner,age,power,brand
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [545]:
df.tail(10)

,bike_name,price,city,kms_driven,owner,age,power,brand
32638,Yamaha Fazer 25 250cc,123000.0,Kadapa,14500.0,First Owner,4.0,250.0,Yamaha
32639,Royal Enfield Classic 350cc,95500.0,Delhi,18000.0,First Owner,8.0,350.0,Royal Enfield
32640,Hero Passion Pro 100cc,32000.0,Delhi,12000.0,First Owner,6.0,100.0,Hero
32641,Bajaj Avenger 220cc,41000.0,Delhi,20245.0,Second Owner,11.0,220.0,Bajaj
32642,Hero Passion 100cc,15000.0,Perumbavoor,35000.0,Second Owner,19.0,100.0,Hero
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [546]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32648 entries, 0 to 32647
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   32648 non-null  str
 1   price       32648 non-null  float64
 2   city        32648 non-null  str
 3   kms_driven  32648 non-null  float64
 4   owner       32648 non-null  str
 5   age         32648 non-null  float64
 6   power       32648 non-null  float64
 7   brand       32648 non-null  str
dtypes: float64(4), str(4)
memory usage: 2.0 MB

In [547]:
df.columns

Index(['bike_name', 'price', 'city', 'kms_driven', 'owner', 'age', 'power',
       'brand'],
      dtype='str')

In [548]:
df["bike_name"]             #return specific column data

0          TVS Star City Plus Dual Tone 110cc
1                 Royal Enfield Classic 350cc
2                        Triumph Daytona 675R
3                        TVS Apache RTR 180cc
4        Yamaha FZ S V 2.0 150cc-Ltd. Edition
                         ...
32643                  Hero Passion Pro 100cc
32644                    TVS Apache RTR 180cc
32645                Bajaj Avenger Street 220
32646               Hero Super Splendor 125cc
32647                      Bajaj Pulsar 150cc
Name: bike_name, Length: 32648, dtype: str

In [549]:
df[["brand"]]           #return specific column data in data frame

               brand
0                TVS
1      Royal Enfield
2            Triumph
3                TVS
4             Yamaha
...              ...
32643           Hero
32644            TVS
32645          Bajaj
32646           Hero
32647          Bajaj

[32648 rows x 1 columns]

In [550]:
df[["age","brand"]]

        age          brand
0       3.0            TVS
1       4.0  Royal Enfield
2       8.0        Triumph
3       4.0            TVS
4       3.0         Yamaha
...     ...            ...
32643   4.0           Hero
32644   9.0            TVS
32645   6.0          Bajaj
32646  16.0           Hero
32647  13.0          Bajaj

[32648 rows x 2 columns]

In [551]:
df["brand"].unique()                #returns uniques values

<StringArray>
[            'TVS',   'Royal Enfield',         'Triumph',          'Yamaha',
           'Honda',            'Hero',           'Bajaj',          'Suzuki',
         'Benelli',             'KTM',        'Mahindra',        'Kawasaki',
          'Ducati',         'Hyosung', 'Harley-Davidson',            'Jawa',
             'BMW',          'Indian',         'Rajdoot',             'LML',
           'Yezdi',              'MV',           'Ideal']
Length: 23, dtype: str

In [552]:
df["owner"].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [553]:
df["age"].unique()

array([ 3.,  4.,  8.,  6.,  7.,  5.,  2., 16., 13.,  9., 10., 14., 12.,
       11.,  1., 15., 39., 17., 18., 30., 19., 23., 41., 27., 37., 24.,
       20., 43., 38., 63., 34., 31., 22., 26., 25.])

In [554]:
df["brand"].nunique()               #returns numbr of unique values

23

In [555]:
df["brand"].value_counts()

brand
Bajaj              11213
Hero                6368
Royal Enfield       4178
Yamaha              3916
Honda               2108
Suzuki              1464
TVS                 1247
KTM                 1077
Harley-Davidson      737
Kawasaki              79
Hyosung               64
Benelli               56
Mahindra              55
Triumph               26
Ducati                22
BMW                   16
Jawa                  10
MV                     4
Indian                 3
Ideal                  2
Rajdoot                1
LML                    1
Yezdi                  1
Name: count, dtype: int64

In [556]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
32643     True
32644     True
32645     True
32646     True
32647     True
Length: 32648, dtype: bool

In [557]:
df.duplicated().sum()

np.int64(25324)

In [558]:
df.drop_duplicates()

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [559]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [560]:
df.drop_duplicates(inplace=True)            #inplace = True permanently makes change in data frame

In [561]:
df.duplicated().sum()

np.int64(0)

In [562]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [563]:
df.isna().sum()

bike_name     0
price         0
city          0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [564]:
df.dropna()         #to remove null values

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [565]:
#y = mx + c   
df.info()

<class 'pandas.DataFrame'>
Index: 7324 entries, 0 to 9372
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   7324 non-null   str
 1   price       7324 non-null   float64
 2   city        7324 non-null   str
 3   kms_driven  7324 non-null   float64
 4   owner       7324 non-null   str
 5   age         7324 non-null   float64
 6   power       7324 non-null   float64
 7   brand       7324 non-null   str
dtypes: float64(4), str(4)
memory usage: 515.0 KB

In [566]:
df['owner'].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [567]:
owner_dict = {
 'First Owner':1, 'Second Owner':2, 'Third Owner':3, 'Fourth Owner Or More':4   
}

In [568]:
# df['owner']=df['owner'].map(owner_dict)

In [569]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [570]:
df.info()

<class 'pandas.DataFrame'>
Index: 7324 entries, 0 to 9372
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   7324 non-null   str
 1   price       7324 non-null   float64
 2   city        7324 non-null   str
 3   kms_driven  7324 non-null   float64
 4   owner       7324 non-null   str
 5   age         7324 non-null   float64
 6   power       7324 non-null   float64
 7   brand       7324 non-null   str
dtypes: float64(4), str(4)
memory usage: 515.0 KB

In [571]:
# df.drop('city',axis=1,inplace=True)

In [572]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [573]:
# df.drop(['age','power'],axis=1)

In [574]:
df['brand'].unique()

<StringArray>
[            'TVS',   'Royal Enfield',         'Triumph',          'Yamaha',
           'Honda',            'Hero',           'Bajaj',          'Suzuki',
         'Benelli',             'KTM',        'Mahindra',        'Kawasaki',
          'Ducati',         'Hyosung', 'Harley-Davidson',            'Jawa',
             'BMW',          'Indian',         'Rajdoot',             'LML',
           'Yezdi',              'MV',           'Ideal']
Length: 23, dtype: str

In [575]:
brand_dict = {
     'TVS':1, 'Royal Enfield':2,         'Triumph':3,          'Yamaha':4,
           'Honda':5,            'Hero':6,           'Bajaj':7,          'Suzuki':8,
         'Benelli':9,             'KTM':10,        'Mahindra':11,        'Kawasaki':12,
          'Ducati':13,         'Hyosung':14, 'Harley-Davidson':15,            'Jawa':16,
             'BMW':17,          'Indian':18,         'Rajdoot':19,             'LML':20,
           'Yezdi':21,              'MV':22,           'Ideal':23
}

In [576]:
# df['brand']=df['brand'].map(brand_dict)

In [577]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [578]:
df.info()

<class 'pandas.DataFrame'>
Index: 7324 entries, 0 to 9372
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   7324 non-null   str
 1   price       7324 non-null   float64
 2   city        7324 non-null   str
 3   kms_driven  7324 non-null   float64
 4   owner       7324 non-null   str
 5   age         7324 non-null   float64
 6   power       7324 non-null   float64
 7   brand       7324 non-null   str
dtypes: float64(4), str(4)
memory usage: 515.0 KB

In [579]:
obj_val = df.select_dtypes(include='object')

C:\Users\user\AppData\Local\Temp\ipykernel_7828\3590679278.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_val = df.select_dtypes(include='object')

In [580]:
obj_val

,bike_name,city,owner,brand
0,TVS Star City Plus Dual Tone 110cc,Ahmedabad,First Owner,TVS
1,Royal Enfield Classic 350cc,Delhi,First Owner,Royal Enfield
2,Triumph Daytona 675R,Delhi,First Owner,Triumph
3,TVS Apache RTR 180cc,Bangalore,First Owner,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,Bangalore,First Owner,Yamaha
...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,Delhi,First Owner,Hero
9369,Bajaj Avenger 220cc,Bangalore,First Owner,Bajaj
9370,Harley-Davidson Street 750 ABS,Jodhpur,First Owner,Harley-Davidson
9371,Bajaj Dominar 400 ABS,Hyderabad,First Owner,Bajaj
9372,Bajaj Avenger Street 220,Hyderabad,First Owner,Bajaj

In [581]:
num_val = df.select_dtypes(exclude='object')

In [582]:
num_val

         price  kms_driven  age  power
0      35000.0     17654.0  3.0  110.0
1     119900.0     11000.0  4.0  350.0
2     600000.0       110.0  8.0  675.0
3      65000.0     16329.0  4.0  180.0
4      80000.0     10000.0  3.0  150.0
...        ...         ...  ...    ...
9362   25000.0     48587.0  8.0  150.0
9369   35000.0     60000.0  9.0  220.0
9370  450000.0      3430.0  4.0  750.0
9371  139000.0     21300.0  4.0  400.0
9372   80000.0      7127.0  5.0  220.0

[7324 rows x 4 columns]

In [583]:
complete_data = pd.concat([obj_val,num_val],axis=1)

In [584]:
complete_data

,bike_name,city,owner,brand,price,kms_driven,age,power
0,TVS Star City Plus Dual Tone 110cc,Ahmedabad,First Owner,TVS,35000.0,17654.0,3.0,110.0
1,Royal Enfield Classic 350cc,Delhi,First Owner,Royal Enfield,119900.0,11000.0,4.0,350.0
2,Triumph Daytona 675R,Delhi,First Owner,Triumph,600000.0,110.0,8.0,675.0
3,TVS Apache RTR 180cc,Bangalore,First Owner,TVS,65000.0,16329.0,4.0,180.0
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,Bangalore,First Owner,Yamaha,80000.0,10000.0,3.0,150.0
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,Delhi,First Owner,Hero,25000.0,48587.0,8.0,150.0
9369,Bajaj Avenger 220cc,Bangalore,First Owner,Bajaj,35000.0,60000.0,9.0,220.0
9370,Harley-Davidson Street 750 ABS,Jodhpur,First Owner,Harley-Davidson,450000.0,3430.0,4.0,750.0
9371,Bajaj Dominar 400 ABS,Hyderabad,First Owner,Bajaj,139000.0,21300.0,4.0,400.0
9372,Bajaj Avenger Street 220,Hyderabad,First Owner,Bajaj,80000.0,7127.0,5.0,220.0

In [585]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [586]:
tvs_brand = df[df['brand']=='TVS']

In [587]:
tvs_brand

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
52,TVS Apache RTR 160cc,60000.0,Mumbai,30000.0,First Owner,5.0,160.0,TVS
114,TVS Apache RTR 160 4V Disc,69900.0,Delhi,8700.0,First Owner,3.0,160.0,TVS
130,TVS Phoenix Disc 125cc,21500.0,Barasat,10500.0,First Owner,5.0,125.0,TVS
...,...,...,...,...,...,...,...,...
9247,TVS Apache RTR 160cc Rear Disc,70000.0,Ghaziabad,4116.0,First Owner,3.0,160.0,TVS
9307,TVS Apache RTR 160cc,30000.0,Alibag,30000.0,First Owner,10.0,160.0,TVS
9312,TVS Apache RTR 200 4V FI,65450.0,Delhi,9238.0,First Owner,3.0,200.0,TVS
9320,TVS Apache 150cc,20000.0,Hissar,84916.0,First Owner,14.0,150.0,TVS
9322,TVS Radeon 110cc Drum SBT,58000.0,Delhi,4020.0,First Owner,2.0,110.0,TVS

In [588]:
tvs_brand['owner'].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner']
Length: 3, dtype: str

In [589]:
tvs_first = tvs_brand[tvs_brand['owner']=='First Owner']

In [590]:
tvs_first

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
52,TVS Apache RTR 160cc,60000.0,Mumbai,30000.0,First Owner,5.0,160.0,TVS
114,TVS Apache RTR 160 4V Disc,69900.0,Delhi,8700.0,First Owner,3.0,160.0,TVS
130,TVS Phoenix Disc 125cc,21500.0,Barasat,10500.0,First Owner,5.0,125.0,TVS
...,...,...,...,...,...,...,...,...
9247,TVS Apache RTR 160cc Rear Disc,70000.0,Ghaziabad,4116.0,First Owner,3.0,160.0,TVS
9307,TVS Apache RTR 160cc,30000.0,Alibag,30000.0,First Owner,10.0,160.0,TVS
9312,TVS Apache RTR 200 4V FI,65450.0,Delhi,9238.0,First Owner,3.0,200.0,TVS
9320,TVS Apache 150cc,20000.0,Hissar,84916.0,First Owner,14.0,150.0,TVS
9322,TVS Radeon 110cc Drum SBT,58000.0,Delhi,4020.0,First Owner,2.0,110.0,TVS

In [591]:
#duplicated value permannet drop,null drop,str --> num,unnecessary column drop

In [592]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [593]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [594]:
bajaj_brand = df[df['brand']=='Bajaj']

In [595]:
bajaj_brand

,bike_name,price,city,kms_driven,owner,age,power,brand
12,Bajaj Pulsar NS200,78000.0,Bangalore,9900.0,First Owner,4.0,200.0,Bajaj
13,Bajaj Discover 100M,29499.0,Delhi,20000.0,First Owner,8.0,100.0,Bajaj
14,Bajaj Discover 125M,29900.0,Delhi,20000.0,First Owner,7.0,125.0,Bajaj
15,Bajaj Pulsar NS200 ABS,90000.0,Bangalore,11574.0,First Owner,3.0,200.0,Bajaj
16,Bajaj Pulsar RS200 ABS,120000.0,Bangalore,23000.0,First Owner,3.0,200.0,Bajaj
...,...,...,...,...,...,...,...,...
9360,Bajaj Pulsar NS200,48000.0,Allahabad,41939.0,First Owner,8.0,200.0,Bajaj
9361,Bajaj Avenger 220cc,50000.0,Bangalore,29134.0,First Owner,7.0,220.0,Bajaj
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [596]:
bajaj_under2 = bajaj_brand[bajaj_brand['age']<=2]

In [597]:
bajaj_under2

,bike_name,price,city,kms_driven,owner,age,power,brand
43,Bajaj Avenger Street 220 ABS,110000.0,Bangalore,2550.0,First Owner,2.0,220.0,Bajaj
95,Bajaj Pulsar 150cc,60000.0,Pune,2000.0,First Owner,2.0,150.0,Bajaj
141,Bajaj Pulsar NS200,115000.0,Bangalore,5000.0,First Owner,2.0,200.0,Bajaj
237,Bajaj Dominar 400 ABS,190000.0,Mandya,8780.0,First Owner,2.0,400.0,Bajaj
283,Bajaj Pulsar NS200,106000.0,Delhi,1175.0,First Owner,2.0,200.0,Bajaj
340,Bajaj Pulsar 125cc Disc CBS,47000.0,Banki,14009.0,First Owner,2.0,125.0,Bajaj
341,Bajaj Avenger Street 220,95000.0,Delhi,11000.0,First Owner,2.0,220.0,Bajaj
395,Bajaj Pulsar RS200 ABS,130000.0,Mumbai,15000.0,First Owner,2.0,200.0,Bajaj
510,Bajaj Pulsar 150cc,66000.0,Delhi,15000.0,First Owner,2.0,150.0,Bajaj
619,Bajaj V15 150cc POWER UP,35000.0,Mumbai,26000.0,First Owner,2.0,150.0,Bajaj
853,Bajaj Dominar 400 ABS,195000.0,Mumbai,6000.0,First Owner,2.0,400.0,Bajaj
889,Bajaj Pulsar 150cc Rear Disc ABS,85000.0,Balaghat,2500.0,First Owner,2.0,150.0,Bajaj
1340,Bajaj Discover 125cc Disc,39000.0,Faridabad,9923.0,First Owner,2.0,125.0,Bajaj
1401,Bajaj Pulsar 150cc,67000.0,Chennai,6266.0,First Owner,2.0,150.0,Bajaj
1496,Bajaj Pulsar NS200 ABS,105000.0,Mumbai,500.0,First Owner,2.0,200.0,Bajaj
1747,Bajaj Pulsar NS200,120000.0,Delhi,8000.0,First Owner,2.0,200.0,Bajaj
1818,Bajaj CT 100 ES Alloy,39000.0,Faridabad,2564.0,First Owner,2.0,100.0,Bajaj
1819,Bajaj Platina Alloy ES-100cc,39000.0,Faridabad,12193.0,First Owner,2.0,100.0,Bajaj
1893,Bajaj Platina Alloy ES-100cc,38000.0,Faridabad,12692.0,First Owner,2.0,100.0,Bajaj
2173,Bajaj Platina 100cc,39000.0,Faridabad,8491.0,First Owner,2.0,100.0,Bajaj
2185,Bajaj Platina 110 H Gear Disc,43500.0,Jaipur,18346.0,First Owner,2.0,110.0,Bajaj
2782,Bajaj Platina 110 CBS,47000.0,Gurgaon,2860.0,First Owner,2.0,110.0,Bajaj
2838,Bajaj Avenger Cruise 220 ABS,99000.0,Delhi,1958.0,First Owner,2.0,220.0,Bajaj
3101,Bajaj CT110 ES Alloy,48000.0,Bangalore,1850.0,First Owner,2.0,110.0,Bajaj
3134,Bajaj CT 100 ES Alloy,32000.0,Faridabad,12000.0,First Owner,2.0,100.0,Bajaj
3175,Bajaj Avenger Street 160 ABS,85000.0,Mumbai,7000.0,First Owner,2.0,160.0,Bajaj
3807,Bajaj Pulsar NS160,70000.0,Delhi,16880.0,Second Owner,2.0,160.0,Bajaj
3948,Bajaj Avenger Street 160 ABS,80000.0,Delhi,2700.0,First Owner,2.0,160.0,Bajaj
4041,Bajaj Pulsar RS200 ABS,145400.0,Pune,1980.0,First Owner,2.0,200.0,Bajaj
4424,Bajaj Platina 110 CBS,39500.0,Faridabad,14268.0,First Owner,2.0,110.0,Bajaj
4959,Bajaj Platina 110 CBS,55000.0,Ahmedabad,5200.0,First Owner,2.0,110.0,Bajaj
5046,Bajaj Pulsar 150cc,60000.0,Ghaziabad,7312.0,First Owner,2.0,150.0,Bajaj
5477,Bajaj Avenger Cruise 220,85000.0,Falakata,4500.0,First Owner,2.0,220.0,Bajaj
5578,Bajaj Pulsar 220F,93500.0,Thane,199.0,First Owner,2.0,220.0,Bajaj
5707,Bajaj Pulsar NS160 Rear Disc,85000.0,Silchar,3000.0,First Owner,2.0,160.0,Bajaj
5852,Bajaj Avenger Street 220 ABS,45000.0,Chennai,35000.0,Second Owner,2.0,220.0,Bajaj
6060,Bajaj Pulsar RS200 ABS,143000.0,Lucknow,2351.0,First Owner,2.0,200.0,Bajaj
6096,Bajaj Pulsar 150cc,78000.0,Belgaum,12500.0,Second Owner,2.0,150.0,Bajaj
6144,Bajaj Dominar 400 ABS,177500.0,Silchar,3000.0,First Owner,2.0,400.0,Bajaj
6145,Bajaj Dominar 400,150000.0,Bangalore,16000.0,First Owner,2.0,400.0,Bajaj
6516,Bajaj Avenger Street 180,65000.0,Faridabad,6903.0,First Owner,2.0,180.0,Bajaj
6532,Bajaj Platina 100cc,38000.0,Faridabad,15383.0,First Owner,2.0,100.0,Bajaj
6992,Bajaj Avenger Street 160 ABS,80000.0,Delhi,3509.0,First Owner,2.0,160.0,Bajaj
7272,Bajaj CT 100 ES Alloy,38500.0,Faridabad,4877.0,First Owner,2.0,100.0,Bajaj
7354,Bajaj Pulsar 150cc,60000.0,Faridabad,10121.0,First Owner,2.0,150.0,Bajaj
7590,Bajaj Pulsar NS200 ABS,105000.0,Bangalore,7684.0,First Owner,2.0,200.0,Bajaj
7697,Bajaj Pulsar NS200 ABS,105000.0,Chennai,4268.0,First Owner,2.0,200.0,Bajaj
7835,Bajaj CT 100 KS Alloy,40000.0,Chandigarh,1501.0,First Owner,2.0,100.0,Bajaj
8107,Bajaj Pulsar NS160 Rear Disc,97000.0,Tiruppur,78.0,First Owner,2.0,160.0,Bajaj
8335,Bajaj Pulsar 150cc Neon,72000.0,Pune,3162.0,First Owner,2.0,150.0,Bajaj

In [598]:
bajaj_km20k = bajaj_under2[bajaj_under2['kms_driven']<=20000]

In [599]:
bajaj_km20k

,bike_name,price,city,kms_driven,owner,age,power,brand
43,Bajaj Avenger Street 220 ABS,110000.0,Bangalore,2550.0,First Owner,2.0,220.0,Bajaj
95,Bajaj Pulsar 150cc,60000.0,Pune,2000.0,First Owner,2.0,150.0,Bajaj
141,Bajaj Pulsar NS200,115000.0,Bangalore,5000.0,First Owner,2.0,200.0,Bajaj
237,Bajaj Dominar 400 ABS,190000.0,Mandya,8780.0,First Owner,2.0,400.0,Bajaj
283,Bajaj Pulsar NS200,106000.0,Delhi,1175.0,First Owner,2.0,200.0,Bajaj
340,Bajaj Pulsar 125cc Disc CBS,47000.0,Banki,14009.0,First Owner,2.0,125.0,Bajaj
341,Bajaj Avenger Street 220,95000.0,Delhi,11000.0,First Owner,2.0,220.0,Bajaj
395,Bajaj Pulsar RS200 ABS,130000.0,Mumbai,15000.0,First Owner,2.0,200.0,Bajaj
510,Bajaj Pulsar 150cc,66000.0,Delhi,15000.0,First Owner,2.0,150.0,Bajaj
853,Bajaj Dominar 400 ABS,195000.0,Mumbai,6000.0,First Owner,2.0,400.0,Bajaj
889,Bajaj Pulsar 150cc Rear Disc ABS,85000.0,Balaghat,2500.0,First Owner,2.0,150.0,Bajaj
1340,Bajaj Discover 125cc Disc,39000.0,Faridabad,9923.0,First Owner,2.0,125.0,Bajaj
1401,Bajaj Pulsar 150cc,67000.0,Chennai,6266.0,First Owner,2.0,150.0,Bajaj
1496,Bajaj Pulsar NS200 ABS,105000.0,Mumbai,500.0,First Owner,2.0,200.0,Bajaj
1747,Bajaj Pulsar NS200,120000.0,Delhi,8000.0,First Owner,2.0,200.0,Bajaj
1818,Bajaj CT 100 ES Alloy,39000.0,Faridabad,2564.0,First Owner,2.0,100.0,Bajaj
1819,Bajaj Platina Alloy ES-100cc,39000.0,Faridabad,12193.0,First Owner,2.0,100.0,Bajaj
1893,Bajaj Platina Alloy ES-100cc,38000.0,Faridabad,12692.0,First Owner,2.0,100.0,Bajaj
2173,Bajaj Platina 100cc,39000.0,Faridabad,8491.0,First Owner,2.0,100.0,Bajaj
2185,Bajaj Platina 110 H Gear Disc,43500.0,Jaipur,18346.0,First Owner,2.0,110.0,Bajaj
2782,Bajaj Platina 110 CBS,47000.0,Gurgaon,2860.0,First Owner,2.0,110.0,Bajaj
2838,Bajaj Avenger Cruise 220 ABS,99000.0,Delhi,1958.0,First Owner,2.0,220.0,Bajaj
3101,Bajaj CT110 ES Alloy,48000.0,Bangalore,1850.0,First Owner,2.0,110.0,Bajaj
3134,Bajaj CT 100 ES Alloy,32000.0,Faridabad,12000.0,First Owner,2.0,100.0,Bajaj
3175,Bajaj Avenger Street 160 ABS,85000.0,Mumbai,7000.0,First Owner,2.0,160.0,Bajaj
3807,Bajaj Pulsar NS160,70000.0,Delhi,16880.0,Second Owner,2.0,160.0,Bajaj
3948,Bajaj Avenger Street 160 ABS,80000.0,Delhi,2700.0,First Owner,2.0,160.0,Bajaj
4041,Bajaj Pulsar RS200 ABS,145400.0,Pune,1980.0,First Owner,2.0,200.0,Bajaj
4424,Bajaj Platina 110 CBS,39500.0,Faridabad,14268.0,First Owner,2.0,110.0,Bajaj
4959,Bajaj Platina 110 CBS,55000.0,Ahmedabad,5200.0,First Owner,2.0,110.0,Bajaj
5046,Bajaj Pulsar 150cc,60000.0,Ghaziabad,7312.0,First Owner,2.0,150.0,Bajaj
5477,Bajaj Avenger Cruise 220,85000.0,Falakata,4500.0,First Owner,2.0,220.0,Bajaj
5578,Bajaj Pulsar 220F,93500.0,Thane,199.0,First Owner,2.0,220.0,Bajaj
5707,Bajaj Pulsar NS160 Rear Disc,85000.0,Silchar,3000.0,First Owner,2.0,160.0,Bajaj
6060,Bajaj Pulsar RS200 ABS,143000.0,Lucknow,2351.0,First Owner,2.0,200.0,Bajaj
6096,Bajaj Pulsar 150cc,78000.0,Belgaum,12500.0,Second Owner,2.0,150.0,Bajaj
6144,Bajaj Dominar 400 ABS,177500.0,Silchar,3000.0,First Owner,2.0,400.0,Bajaj
6145,Bajaj Dominar 400,150000.0,Bangalore,16000.0,First Owner,2.0,400.0,Bajaj
6516,Bajaj Avenger Street 180,65000.0,Faridabad,6903.0,First Owner,2.0,180.0,Bajaj
6532,Bajaj Platina 100cc,38000.0,Faridabad,15383.0,First Owner,2.0,100.0,Bajaj
6992,Bajaj Avenger Street 160 ABS,80000.0,Delhi,3509.0,First Owner,2.0,160.0,Bajaj
7272,Bajaj CT 100 ES Alloy,38500.0,Faridabad,4877.0,First Owner,2.0,100.0,Bajaj
7354,Bajaj Pulsar 150cc,60000.0,Faridabad,10121.0,First Owner,2.0,150.0,Bajaj
7590,Bajaj Pulsar NS200 ABS,105000.0,Bangalore,7684.0,First Owner,2.0,200.0,Bajaj
7697,Bajaj Pulsar NS200 ABS,105000.0,Chennai,4268.0,First Owner,2.0,200.0,Bajaj
7835,Bajaj CT 100 KS Alloy,40000.0,Chandigarh,1501.0,First Owner,2.0,100.0,Bajaj
8107,Bajaj Pulsar NS160 Rear Disc,97000.0,Tiruppur,78.0,First Owner,2.0,160.0,Bajaj
8335,Bajaj Pulsar 150cc Neon,72000.0,Pune,3162.0,First Owner,2.0,150.0,Bajaj

In [600]:
royalenfield = df[df['brand']=='Royal Enfield']

In [601]:
royalenfield

,bike_name,price,city,kms_driven,owner,age,power,brand
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
8,Royal Enfield Thunderbird X 350cc,145000.0,Bangalore,9190.0,First Owner,3.0,350.0,Royal Enfield
9,Royal Enfield Classic Desert Storm 500cc,88000.0,Delhi,19000.0,Second Owner,7.0,500.0,Royal Enfield
23,Royal Enfield Classic Chrome 500cc,121700.0,Kalyan,24520.0,First Owner,5.0,500.0,Royal Enfield
36,Royal Enfield Classic 350cc,98800.0,Kochi,39000.0,First Owner,5.0,350.0,Royal Enfield
...,...,...,...,...,...,...,...,...
9261,Royal Enfield Classic 500cc,146006.0,Guwahati,8575.0,First Owner,4.0,500.0,Royal Enfield
9319,Royal Enfield Classic 350cc,100000.0,Chennai,25000.0,First Owner,10.0,350.0,Royal Enfield
9337,Royal Enfield Himalayan 410cc,120000.0,Gurgaon,8492.0,First Owner,5.0,410.0,Royal Enfield
9338,Royal Enfield Himalayan 410cc,138000.0,Delhi,5000.0,First Owner,5.0,410.0,Royal Enfield
9344,Royal Enfield Bullet Twinspark 350cc,80000.0,Delhi,56968.0,First Owner,8.0,350.0,Royal Enfield

In [602]:
royal1 = royalenfield[royalenfield['owner']=='Third Owner']

In [603]:
royal1

,bike_name,price,city,kms_driven,owner,age,power,brand
766,Royal Enfield Bullet Electra Twinspark 350cc,85000.0,Palwal,23399.0,Third Owner,6.0,350.0,Royal Enfield
1225,Royal Enfield Thunderbird 500cc,119000.0,Bangalore,11976.0,Third Owner,6.0,500.0,Royal Enfield
2796,Royal Enfield Thunderbird 500cc,95000.0,Ahmedabad,30000.0,Third Owner,8.0,500.0,Royal Enfield
2978,Royal Enfield‎ Bullet 350cc,95000.0,Bangalore,50000.0,Third Owner,43.0,350.0,Royal Enfield
4681,Royal Enfield Thunderbird 350cc,75000.0,Bardhaman,22000.0,Third Owner,10.0,350.0,Royal Enfield
5790,Royal Enfield Bullet Electra 350cc,55000.0,Delhi,4572.0,Third Owner,17.0,350.0,Royal Enfield
5918,Royal Enfield Thunderbird 350cc,45000.0,Bangalore,93108.0,Third Owner,18.0,350.0,Royal Enfield
6282,Royal Enfield Bullet Electra 350cc,60000.0,Delhi,36000.0,Third Owner,11.0,350.0,Royal Enfield
6685,Royal Enfield‎ Bullet 350cc,120000.0,Bangalore,8000.0,Third Owner,38.0,350.0,Royal Enfield
7860,Royal Enfield‎ Bullet 350cc,65000.0,Gurgaon,14101.0,Third Owner,34.0,350.0,Royal Enfield
8190,Royal Enfield Bullet Electra 350cc,85000.0,Bundi,15000.0,Third Owner,7.0,350.0,Royal Enfield
8396,Royal Enfield Classic 500cc,150000.0,Mathura,17000.0,Third Owner,4.0,500.0,Royal Enfield
8676,Royal Enfield Classic Desert Storm 500cc,92000.0,Ludhiana,23569.0,Third Owner,7.0,500.0,Royal Enfield
9183,Royal Enfield Thunderbird 350cc,35800.0,Bangalore,90408.0,Third Owner,18.0,350.0,Royal Enfield

In [604]:
royalprice = royal1[royal1['price']<=150000]

In [605]:
royalprice

,bike_name,price,city,kms_driven,owner,age,power,brand
766,Royal Enfield Bullet Electra Twinspark 350cc,85000.0,Palwal,23399.0,Third Owner,6.0,350.0,Royal Enfield
1225,Royal Enfield Thunderbird 500cc,119000.0,Bangalore,11976.0,Third Owner,6.0,500.0,Royal Enfield
2796,Royal Enfield Thunderbird 500cc,95000.0,Ahmedabad,30000.0,Third Owner,8.0,500.0,Royal Enfield
2978,Royal Enfield‎ Bullet 350cc,95000.0,Bangalore,50000.0,Third Owner,43.0,350.0,Royal Enfield
4681,Royal Enfield Thunderbird 350cc,75000.0,Bardhaman,22000.0,Third Owner,10.0,350.0,Royal Enfield
5790,Royal Enfield Bullet Electra 350cc,55000.0,Delhi,4572.0,Third Owner,17.0,350.0,Royal Enfield
5918,Royal Enfield Thunderbird 350cc,45000.0,Bangalore,93108.0,Third Owner,18.0,350.0,Royal Enfield
6282,Royal Enfield Bullet Electra 350cc,60000.0,Delhi,36000.0,Third Owner,11.0,350.0,Royal Enfield
6685,Royal Enfield‎ Bullet 350cc,120000.0,Bangalore,8000.0,Third Owner,38.0,350.0,Royal Enfield
7860,Royal Enfield‎ Bullet 350cc,65000.0,Gurgaon,14101.0,Third Owner,34.0,350.0,Royal Enfield
8190,Royal Enfield Bullet Electra 350cc,85000.0,Bundi,15000.0,Third Owner,7.0,350.0,Royal Enfield
8396,Royal Enfield Classic 500cc,150000.0,Mathura,17000.0,Third Owner,4.0,500.0,Royal Enfield
8676,Royal Enfield Classic Desert Storm 500cc,92000.0,Ludhiana,23569.0,Third Owner,7.0,500.0,Royal Enfield
9183,Royal Enfield Thunderbird 350cc,35800.0,Bangalore,90408.0,Third Owner,18.0,350.0,Royal Enfield

In [606]:
royal_kmdriven = royalprice[royalprice['kms_driven']<150000]

In [607]:
royal_kmdriven

,bike_name,price,city,kms_driven,owner,age,power,brand
766,Royal Enfield Bullet Electra Twinspark 350cc,85000.0,Palwal,23399.0,Third Owner,6.0,350.0,Royal Enfield
1225,Royal Enfield Thunderbird 500cc,119000.0,Bangalore,11976.0,Third Owner,6.0,500.0,Royal Enfield
2796,Royal Enfield Thunderbird 500cc,95000.0,Ahmedabad,30000.0,Third Owner,8.0,500.0,Royal Enfield
2978,Royal Enfield‎ Bullet 350cc,95000.0,Bangalore,50000.0,Third Owner,43.0,350.0,Royal Enfield
4681,Royal Enfield Thunderbird 350cc,75000.0,Bardhaman,22000.0,Third Owner,10.0,350.0,Royal Enfield
5790,Royal Enfield Bullet Electra 350cc,55000.0,Delhi,4572.0,Third Owner,17.0,350.0,Royal Enfield
5918,Royal Enfield Thunderbird 350cc,45000.0,Bangalore,93108.0,Third Owner,18.0,350.0,Royal Enfield
6282,Royal Enfield Bullet Electra 350cc,60000.0,Delhi,36000.0,Third Owner,11.0,350.0,Royal Enfield
6685,Royal Enfield‎ Bullet 350cc,120000.0,Bangalore,8000.0,Third Owner,38.0,350.0,Royal Enfield
7860,Royal Enfield‎ Bullet 350cc,65000.0,Gurgaon,14101.0,Third Owner,34.0,350.0,Royal Enfield
8190,Royal Enfield Bullet Electra 350cc,85000.0,Bundi,15000.0,Third Owner,7.0,350.0,Royal Enfield
8396,Royal Enfield Classic 500cc,150000.0,Mathura,17000.0,Third Owner,4.0,500.0,Royal Enfield
8676,Royal Enfield Classic Desert Storm 500cc,92000.0,Ludhiana,23569.0,Third Owner,7.0,500.0,Royal Enfield
9183,Royal Enfield Thunderbird 350cc,35800.0,Bangalore,90408.0,Third Owner,18.0,350.0,Royal Enfield

In [608]:
royalage = royal_kmdriven[royal_kmdriven['age']<=2]

In [609]:
royalage

Empty DataFrame
Columns: [bike_name, price, city, kms_driven, owner, age, power, brand]
Index: []

In [610]:
df[(df['brand']=='Royal Enfield') & (df['age']<=2) & (df['price']<=150000)]

,bike_name,price,city,kms_driven,owner,age,power,brand
194,Royal Enfield Electra 350cc,145000.0,Bangalore,4000.0,First Owner,2.0,350.0,Royal Enfield
479,Royal Enfield Classic 350cc,150000.0,Delhi,4000.0,First Owner,2.0,350.0,Royal Enfield
1006,Royal Enfield Thunderbird 350cc ABS,148000.0,Haldwani,7300.0,First Owner,2.0,350.0,Royal Enfield
1203,Royal Enfield Classic Gunmetal Grey 350cc ABS,150000.0,Bardhaman,1800.0,First Owner,2.0,350.0,Royal Enfield
1681,Royal Enfield Thunderbird X 350cc ABS,135000.0,Sibsagar,3800.0,First Owner,2.0,350.0,Royal Enfield
1716,Royal Enfield Thunderbird 350cc ABS,144700.0,Kharar,770.0,First Owner,2.0,350.0,Royal Enfield
1749,Royal Enfield Bullet Twinspark Kickstart 350cc,145000.0,Delhi,5000.0,First Owner,2.0,350.0,Royal Enfield
2982,Royal Enfield Classic 350cc-Redditch Edition,137000.0,Sultanpur,8400.0,First Owner,2.0,350.0,Royal Enfield
5495,Royal Enfield Classic 350cc,150000.0,Kota,1947.0,First Owner,2.0,350.0,Royal Enfield
5939,Royal Enfield Bullet Twinspark Kickstart 350cc,105000.0,Faridabad,7255.0,First Owner,2.0,350.0,Royal Enfield
6090,Royal Enfield Bullet Electra Twinspark 350CC ABS,127000.0,Mumbai,83.0,First Owner,2.0,350.0,Royal Enfield
6298,Royal Enfield Bullet Electra Twinspark 350CC ABS,140000.0,Mumbai,2000.0,First Owner,2.0,350.0,Royal Enfield
6329,Royal Enfield Electra 350cc,130000.0,Faridabad,3688.0,First Owner,2.0,350.0,Royal Enfield
6590,Royal Enfield Classic 350cc,130000.0,Ghaziabad,19249.0,First Owner,2.0,350.0,Royal Enfield
7019,Royal Enfield Electra 350cc,135000.0,Ahmedabad,10779.0,First Owner,2.0,350.0,Royal Enfield
7294,Royal Enfield Classic 350cc-Redditch Edition,133500.0,Mumbai,1608.0,First Owner,2.0,350.0,Royal Enfield
8192,Royal Enfield Thunderbird 350cc ABS,145000.0,Ghaziabad,12400.0,First Owner,2.0,350.0,Royal Enfield

In [611]:
df.query("brand=='Royal Enfield' and age<=2 and kms_driven<50000")

,bike_name,price,city,kms_driven,owner,age,power,brand
38,Royal Enfield Thunderbird X 500cc,190500.0,Samastipur,4550.0,First Owner,2.0,500.0,Royal Enfield
81,Royal Enfield Interceptor 650cc,260000.0,Navi Mumbai,3800.0,First Owner,2.0,650.0,Royal Enfield
139,Royal Enfield Himalayan 410cc Fi ABS,173300.0,Vadodara,14000.0,First Owner,2.0,410.0,Royal Enfield
194,Royal Enfield Electra 350cc,145000.0,Bangalore,4000.0,First Owner,2.0,350.0,Royal Enfield
222,Royal Enfield Himalayan 410cc Fi ABS,177982.0,Hamirpur(hp),7000.0,First Owner,2.0,410.0,Royal Enfield
...,...,...,...,...,...,...,...,...
7294,Royal Enfield Classic 350cc-Redditch Edition,133500.0,Mumbai,1608.0,First Owner,2.0,350.0,Royal Enfield
7694,Royal Enfield Classic Chrome 500cc ABS,215000.0,Delhi,417.0,First Owner,2.0,500.0,Royal Enfield
8139,Royal Enfield Thunderbird X 350cc ABS,169000.0,Bangalore,4411.0,First Owner,2.0,350.0,Royal Enfield
8192,Royal Enfield Thunderbird 350cc ABS,145000.0,Ghaziabad,12400.0,First Owner,2.0,350.0,Royal Enfield
8836,Royal Enfield Thunderbird X 350cc ABS,170200.0,Mumbai,1000.0,First Owner,2.0,350.0,Royal Enfield

In [612]:
df.drop(['bike_name','city'],axis=1,inplace=True)

In [613]:
df.duplicated().sum()

np.int64(18)

In [614]:
df.drop_duplicates()

         price  kms_driven        owner  age  power            brand
0      35000.0     17654.0  First Owner  3.0  110.0              TVS
1     119900.0     11000.0  First Owner  4.0  350.0    Royal Enfield
2     600000.0       110.0  First Owner  8.0  675.0          Triumph
3      65000.0     16329.0  First Owner  4.0  180.0              TVS
4      80000.0     10000.0  First Owner  3.0  150.0           Yamaha
...        ...         ...          ...  ...    ...              ...
9362   25000.0     48587.0  First Owner  8.0  150.0             Hero
9369   35000.0     60000.0  First Owner  9.0  220.0            Bajaj
9370  450000.0      3430.0  First Owner  4.0  750.0  Harley-Davidson
9371  139000.0     21300.0  First Owner  4.0  400.0            Bajaj
9372   80000.0      7127.0  First Owner  5.0  220.0            Bajaj

[7306 rows x 6 columns]

In [615]:
df

         price  kms_driven        owner  age  power            brand
0      35000.0     17654.0  First Owner  3.0  110.0              TVS
1     119900.0     11000.0  First Owner  4.0  350.0    Royal Enfield
2     600000.0       110.0  First Owner  8.0  675.0          Triumph
3      65000.0     16329.0  First Owner  4.0  180.0              TVS
4      80000.0     10000.0  First Owner  3.0  150.0           Yamaha
...        ...         ...          ...  ...    ...              ...
9362   25000.0     48587.0  First Owner  8.0  150.0             Hero
9369   35000.0     60000.0  First Owner  9.0  220.0            Bajaj
9370  450000.0      3430.0  First Owner  4.0  750.0  Harley-Davidson
9371  139000.0     21300.0  First Owner  4.0  400.0            Bajaj
9372   80000.0      7127.0  First Owner  5.0  220.0            Bajaj

[7324 rows x 6 columns]

In [616]:
x = df.drop('price',axis=1)
y = df[['price']]

In [617]:
x

      kms_driven        owner  age  power            brand
0        17654.0  First Owner  3.0  110.0              TVS
1        11000.0  First Owner  4.0  350.0    Royal Enfield
2          110.0  First Owner  8.0  675.0          Triumph
3        16329.0  First Owner  4.0  180.0              TVS
4        10000.0  First Owner  3.0  150.0           Yamaha
...          ...          ...  ...    ...              ...
9362     48587.0  First Owner  8.0  150.0             Hero
9369     60000.0  First Owner  9.0  220.0            Bajaj
9370      3430.0  First Owner  4.0  750.0  Harley-Davidson
9371     21300.0  First Owner  4.0  400.0            Bajaj
9372      7127.0  First Owner  5.0  220.0            Bajaj

[7324 rows x 5 columns]

In [618]:
y

         price
0      35000.0
1     119900.0
2     600000.0
3      65000.0
4      80000.0
...        ...
9362   25000.0
9369   35000.0
9370  450000.0
9371  139000.0
9372   80000.0

[7324 rows x 1 columns]

In [619]:
df.to_csv("clean_bike.csv")