In [111]:
import numpy as np
import pandas as pd

In [112]:
df = pd.read_csv(r"C:\Users\user\OneDrive\Desktop\Data Science\Pandas\Used_Bikes.csv")
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [113]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
32643     True
32644     True
32645     True
32646     True
32647     True
Length: 32648, dtype: bool

In [114]:
df.drop_duplicates(inplace=True)
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [115]:
df.isna().sum()

bike_name     0
price         0
city          0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [116]:
df.info()

<class 'pandas.DataFrame'>
Index: 7324 entries, 0 to 9372
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   7324 non-null   str
 1   price       7324 non-null   float64
 2   city        7324 non-null   str
 3   kms_driven  7324 non-null   float64
 4   owner       7324 non-null   str
 5   age         7324 non-null   float64
 6   power       7324 non-null   float64
 7   brand       7324 non-null   str
dtypes: float64(4), str(4)
memory usage: 515.0 KB

In [117]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [118]:
df.drop(['bike_name','city'],axis=1,inplace=True)

In [119]:
df['brand'].unique()

<StringArray>
[            'TVS',   'Royal Enfield',         'Triumph',          'Yamaha',
           'Honda',            'Hero',           'Bajaj',          'Suzuki',
         'Benelli',             'KTM',        'Mahindra',        'Kawasaki',
          'Ducati',         'Hyosung', 'Harley-Davidson',            'Jawa',
             'BMW',          'Indian',         'Rajdoot',             'LML',
           'Yezdi',              'MV',           'Ideal']
Length: 23, dtype: str

In [120]:
brand_dict = {
     'TVS':1, 'Royal Enfield':2,         'Triumph':3,          'Yamaha':4,
           'Honda':5,            'Hero':6,           'Bajaj':7,          'Suzuki':8,
         'Benelli':9,             'KTM':10,        'Mahindra':11,        'Kawasaki':12,
          'Ducati':13,         'Hyosung':14, 'Harley-Davidson':15,            'Jawa':16,
             'BMW':17,          'Indian':18,         'Rajdoot':19,             'LML':20,
           'Yezdi':21,              'MV':22,           'Ideal':23
}

In [121]:
df['brand']= df['brand'].map(brand_dict)

In [122]:
df

         price  kms_driven        owner  age  power  brand
0      35000.0     17654.0  First Owner  3.0  110.0      1
1     119900.0     11000.0  First Owner  4.0  350.0      2
2     600000.0       110.0  First Owner  8.0  675.0      3
3      65000.0     16329.0  First Owner  4.0  180.0      1
4      80000.0     10000.0  First Owner  3.0  150.0      4
...        ...         ...          ...  ...    ...    ...
9362   25000.0     48587.0  First Owner  8.0  150.0      6
9369   35000.0     60000.0  First Owner  9.0  220.0      7
9370  450000.0      3430.0  First Owner  4.0  750.0     15
9371  139000.0     21300.0  First Owner  4.0  400.0      7
9372   80000.0      7127.0  First Owner  5.0  220.0      7

[7324 rows x 6 columns]

In [123]:
owner_dict = {
 'First Owner':1, 'Second Owner':2, 'Third Owner':3, 'Fourth Owner Or More':4   
}

In [124]:
df['owner'] = df['owner'].map(owner_dict)

In [125]:
df

         price  kms_driven  owner  age  power  brand
0      35000.0     17654.0      1  3.0  110.0      1
1     119900.0     11000.0      1  4.0  350.0      2
2     600000.0       110.0      1  8.0  675.0      3
3      65000.0     16329.0      1  4.0  180.0      1
4      80000.0     10000.0      1  3.0  150.0      4
...        ...         ...    ...  ...    ...    ...
9362   25000.0     48587.0      1  8.0  150.0      6
9369   35000.0     60000.0      1  9.0  220.0      7
9370  450000.0      3430.0      1  4.0  750.0     15
9371  139000.0     21300.0      1  4.0  400.0      7
9372   80000.0      7127.0      1  5.0  220.0      7

[7324 rows x 6 columns]

In [126]:
df.info()

<class 'pandas.DataFrame'>
Index: 7324 entries, 0 to 9372
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   price       7324 non-null   float64
 1   kms_driven  7324 non-null   float64
 2   owner       7324 non-null   int64
 3   age         7324 non-null   float64
 4   power       7324 non-null   float64
 5   brand       7324 non-null   int64
dtypes: float64(4), int64(2)
memory usage: 400.5 KB